"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .fstoperror import FstopError
from typing import Any, TYPE_CHECKING

from fstop.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .badrequest_error import BadRequestError, BadRequestErrorData
    from .fstopdefaulterror import FstopDefaultError
    from .no_response_error import NoResponseError
    from .notfound_error import NotFoundError, NotFoundErrorData
    from .responsevalidationerror import ResponseValidationError
    from .unauthorized_error import UnauthorizedError, UnauthorizedErrorData

__all__ = [
    "BadRequestError",
    "BadRequestErrorData",
    "FstopDefaultError",
    "FstopError",
    "NoResponseError",
    "NotFoundError",
    "NotFoundErrorData",
    "ResponseValidationError",
    "UnauthorizedError",
    "UnauthorizedErrorData",
]

_dynamic_imports: dict[str, str] = {
    "BadRequestError": ".badrequest_error",
    "BadRequestErrorData": ".badrequest_error",
    "FstopDefaultError": ".fstopdefaulterror",
    "NoResponseError": ".no_response_error",
    "NotFoundError": ".notfound_error",
    "NotFoundErrorData": ".notfound_error",
    "ResponseValidationError": ".responsevalidationerror",
    "UnauthorizedError": ".unauthorized_error",
    "UnauthorizedErrorData": ".unauthorized_error",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
