"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from fstop.errors import FstopError
from fstop.types import BaseModel
import httpx
from typing import Optional


class BadRequestErrorData(BaseModel):
    detail: Optional[str] = "Invalid JSON in request body"


@dataclass(unsafe_hash=True)
class BadRequestError(FstopError):
    r"""Serializer for 400 Bad Request responses"""

    data: BadRequestErrorData = field(hash=False)

    def __init__(
        self,
        data: BadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
