"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
from fstop.errors import FstopError
from fstop.types import BaseModel
import httpx
from typing import Optional


class NotFoundErrorData(BaseModel):
    detail: Optional[str] = "The requested resource was not found."


@dataclass(unsafe_hash=True)
class NotFoundError(FstopError):
    r"""Serializer for 404 Not Found responses"""

    data: NotFoundErrorData = field(hash=False)

    def __init__(
        self,
        data: NotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
