"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from fstop.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .booking import (
        Booking,
        BookingClient,
        BookingClientTypedDict,
        BookingProject,
        BookingProjectTypedDict,
        BookingTypedDict,
    )
    from .bookingcreate import BookingCreate, BookingCreateTypedDict
    from .client import Client, ClientTypedDict
    from .clientcreate import ClientCreate, ClientCreateTypedDict
    from .delete_bookingop import DeleteBookingRequest, DeleteBookingRequestTypedDict
    from .delete_clientop import DeleteClientRequest, DeleteClientRequestTypedDict
    from .delete_galleryop import DeleteGalleryRequest, DeleteGalleryRequestTypedDict
    from .delete_projectop import DeleteProjectRequest, DeleteProjectRequestTypedDict
    from .gallery import (
        Gallery,
        GalleryBooking,
        GalleryBookingTypedDict,
        GalleryClient,
        GalleryClientTypedDict,
        GalleryProject,
        GalleryProjectTypedDict,
        GalleryTypedDict,
    )
    from .gallerycreate import GalleryCreate, GalleryCreateTypedDict
    from .obtain_tokenop import ObtainTokenResponse, ObtainTokenResponseTypedDict
    from .partially_update_bookingop import (
        PartiallyUpdateBookingRequest,
        PartiallyUpdateBookingRequestTypedDict,
    )
    from .partially_update_clientop import (
        PartiallyUpdateClientRequest,
        PartiallyUpdateClientRequestTypedDict,
    )
    from .partially_update_galleryop import (
        PartiallyUpdateGalleryRequest,
        PartiallyUpdateGalleryRequestTypedDict,
    )
    from .partially_update_projectop import (
        PartiallyUpdateProjectRequest,
        PartiallyUpdateProjectRequestTypedDict,
    )
    from .patchedbookingcreate import (
        PatchedBookingCreate,
        PatchedBookingCreateTypedDict,
    )
    from .patchedclientcreate import PatchedClientCreate, PatchedClientCreateTypedDict
    from .patchedgallerycreate import (
        PatchedGalleryCreate,
        PatchedGalleryCreateTypedDict,
    )
    from .patchedprojectcreate import (
        PatchedProjectCreate,
        PatchedProjectCreateTypedDict,
    )
    from .project import (
        Project,
        ProjectClient,
        ProjectClientTypedDict,
        ProjectTypedDict,
    )
    from .projectcreate import ProjectCreate, ProjectCreateTypedDict
    from .projecttypeenum import ProjectTypeEnum
    from .refresh_tokenop import RefreshTokenResponse, RefreshTokenResponseTypedDict
    from .retrieve_bookingop import (
        RetrieveBookingRequest,
        RetrieveBookingRequestTypedDict,
    )
    from .retrieve_clientop import RetrieveClientRequest, RetrieveClientRequestTypedDict
    from .retrieve_galleryop import (
        RetrieveGalleryRequest,
        RetrieveGalleryRequestTypedDict,
    )
    from .retrieve_projectop import (
        RetrieveProjectRequest,
        RetrieveProjectRequestTypedDict,
    )
    from .security import Security, SecurityTypedDict
    from .tokenobtainpair import TokenObtainPair, TokenObtainPairTypedDict
    from .tokenrefresh import TokenRefresh, TokenRefreshTypedDict
    from .update_bookingop import UpdateBookingRequest, UpdateBookingRequestTypedDict
    from .update_clientop import UpdateClientRequest, UpdateClientRequestTypedDict
    from .update_galleryop import UpdateGalleryRequest, UpdateGalleryRequestTypedDict
    from .update_projectop import UpdateProjectRequest, UpdateProjectRequestTypedDict

__all__ = [
    "Booking",
    "BookingClient",
    "BookingClientTypedDict",
    "BookingCreate",
    "BookingCreateTypedDict",
    "BookingProject",
    "BookingProjectTypedDict",
    "BookingTypedDict",
    "Client",
    "ClientCreate",
    "ClientCreateTypedDict",
    "ClientTypedDict",
    "DeleteBookingRequest",
    "DeleteBookingRequestTypedDict",
    "DeleteClientRequest",
    "DeleteClientRequestTypedDict",
    "DeleteGalleryRequest",
    "DeleteGalleryRequestTypedDict",
    "DeleteProjectRequest",
    "DeleteProjectRequestTypedDict",
    "Gallery",
    "GalleryBooking",
    "GalleryBookingTypedDict",
    "GalleryClient",
    "GalleryClientTypedDict",
    "GalleryCreate",
    "GalleryCreateTypedDict",
    "GalleryProject",
    "GalleryProjectTypedDict",
    "GalleryTypedDict",
    "ObtainTokenResponse",
    "ObtainTokenResponseTypedDict",
    "PartiallyUpdateBookingRequest",
    "PartiallyUpdateBookingRequestTypedDict",
    "PartiallyUpdateClientRequest",
    "PartiallyUpdateClientRequestTypedDict",
    "PartiallyUpdateGalleryRequest",
    "PartiallyUpdateGalleryRequestTypedDict",
    "PartiallyUpdateProjectRequest",
    "PartiallyUpdateProjectRequestTypedDict",
    "PatchedBookingCreate",
    "PatchedBookingCreateTypedDict",
    "PatchedClientCreate",
    "PatchedClientCreateTypedDict",
    "PatchedGalleryCreate",
    "PatchedGalleryCreateTypedDict",
    "PatchedProjectCreate",
    "PatchedProjectCreateTypedDict",
    "Project",
    "ProjectClient",
    "ProjectClientTypedDict",
    "ProjectCreate",
    "ProjectCreateTypedDict",
    "ProjectTypeEnum",
    "ProjectTypedDict",
    "RefreshTokenResponse",
    "RefreshTokenResponseTypedDict",
    "RetrieveBookingRequest",
    "RetrieveBookingRequestTypedDict",
    "RetrieveClientRequest",
    "RetrieveClientRequestTypedDict",
    "RetrieveGalleryRequest",
    "RetrieveGalleryRequestTypedDict",
    "RetrieveProjectRequest",
    "RetrieveProjectRequestTypedDict",
    "Security",
    "SecurityTypedDict",
    "TokenObtainPair",
    "TokenObtainPairTypedDict",
    "TokenRefresh",
    "TokenRefreshTypedDict",
    "UpdateBookingRequest",
    "UpdateBookingRequestTypedDict",
    "UpdateClientRequest",
    "UpdateClientRequestTypedDict",
    "UpdateGalleryRequest",
    "UpdateGalleryRequestTypedDict",
    "UpdateProjectRequest",
    "UpdateProjectRequestTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "Booking": ".booking",
    "BookingClient": ".booking",
    "BookingClientTypedDict": ".booking",
    "BookingProject": ".booking",
    "BookingProjectTypedDict": ".booking",
    "BookingTypedDict": ".booking",
    "BookingCreate": ".bookingcreate",
    "BookingCreateTypedDict": ".bookingcreate",
    "Client": ".client",
    "ClientTypedDict": ".client",
    "ClientCreate": ".clientcreate",
    "ClientCreateTypedDict": ".clientcreate",
    "DeleteBookingRequest": ".delete_bookingop",
    "DeleteBookingRequestTypedDict": ".delete_bookingop",
    "DeleteClientRequest": ".delete_clientop",
    "DeleteClientRequestTypedDict": ".delete_clientop",
    "DeleteGalleryRequest": ".delete_galleryop",
    "DeleteGalleryRequestTypedDict": ".delete_galleryop",
    "DeleteProjectRequest": ".delete_projectop",
    "DeleteProjectRequestTypedDict": ".delete_projectop",
    "Gallery": ".gallery",
    "GalleryBooking": ".gallery",
    "GalleryBookingTypedDict": ".gallery",
    "GalleryClient": ".gallery",
    "GalleryClientTypedDict": ".gallery",
    "GalleryProject": ".gallery",
    "GalleryProjectTypedDict": ".gallery",
    "GalleryTypedDict": ".gallery",
    "GalleryCreate": ".gallerycreate",
    "GalleryCreateTypedDict": ".gallerycreate",
    "ObtainTokenResponse": ".obtain_tokenop",
    "ObtainTokenResponseTypedDict": ".obtain_tokenop",
    "PartiallyUpdateBookingRequest": ".partially_update_bookingop",
    "PartiallyUpdateBookingRequestTypedDict": ".partially_update_bookingop",
    "PartiallyUpdateClientRequest": ".partially_update_clientop",
    "PartiallyUpdateClientRequestTypedDict": ".partially_update_clientop",
    "PartiallyUpdateGalleryRequest": ".partially_update_galleryop",
    "PartiallyUpdateGalleryRequestTypedDict": ".partially_update_galleryop",
    "PartiallyUpdateProjectRequest": ".partially_update_projectop",
    "PartiallyUpdateProjectRequestTypedDict": ".partially_update_projectop",
    "PatchedBookingCreate": ".patchedbookingcreate",
    "PatchedBookingCreateTypedDict": ".patchedbookingcreate",
    "PatchedClientCreate": ".patchedclientcreate",
    "PatchedClientCreateTypedDict": ".patchedclientcreate",
    "PatchedGalleryCreate": ".patchedgallerycreate",
    "PatchedGalleryCreateTypedDict": ".patchedgallerycreate",
    "PatchedProjectCreate": ".patchedprojectcreate",
    "PatchedProjectCreateTypedDict": ".patchedprojectcreate",
    "Project": ".project",
    "ProjectClient": ".project",
    "ProjectClientTypedDict": ".project",
    "ProjectTypedDict": ".project",
    "ProjectCreate": ".projectcreate",
    "ProjectCreateTypedDict": ".projectcreate",
    "ProjectTypeEnum": ".projecttypeenum",
    "RefreshTokenResponse": ".refresh_tokenop",
    "RefreshTokenResponseTypedDict": ".refresh_tokenop",
    "RetrieveBookingRequest": ".retrieve_bookingop",
    "RetrieveBookingRequestTypedDict": ".retrieve_bookingop",
    "RetrieveClientRequest": ".retrieve_clientop",
    "RetrieveClientRequestTypedDict": ".retrieve_clientop",
    "RetrieveGalleryRequest": ".retrieve_galleryop",
    "RetrieveGalleryRequestTypedDict": ".retrieve_galleryop",
    "RetrieveProjectRequest": ".retrieve_projectop",
    "RetrieveProjectRequestTypedDict": ".retrieve_projectop",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "TokenObtainPair": ".tokenobtainpair",
    "TokenObtainPairTypedDict": ".tokenobtainpair",
    "TokenRefresh": ".tokenrefresh",
    "TokenRefreshTypedDict": ".tokenrefresh",
    "UpdateBookingRequest": ".update_bookingop",
    "UpdateBookingRequestTypedDict": ".update_bookingop",
    "UpdateClientRequest": ".update_clientop",
    "UpdateClientRequestTypedDict": ".update_clientop",
    "UpdateGalleryRequest": ".update_galleryop",
    "UpdateGalleryRequestTypedDict": ".update_galleryop",
    "UpdateProjectRequest": ".update_projectop",
    "UpdateProjectRequestTypedDict": ".update_projectop",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
