"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from fstop.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .booking_input import BookingInput, BookingInputTypedDict
    from .booking_output import (
        BookingClient,
        BookingClientTypedDict,
        BookingOutput,
        BookingOutputTypedDict,
        BookingProject,
        BookingProjectTypedDict,
    )
    from .bookingcreate import BookingCreate, BookingCreateTypedDict
    from .bookings_partial_updateop import (
        BookingsPartialUpdateRequest,
        BookingsPartialUpdateRequestTypedDict,
    )
    from .bookings_updateop import BookingsUpdateRequest, BookingsUpdateRequestTypedDict
    from .client import Client, ClientTypedDict
    from .client_input import ClientInput, ClientInputTypedDict
    from .clientcreate import ClientCreate, ClientCreateTypedDict
    from .clients_partial_updateop import (
        ClientsPartialUpdateRequest,
        ClientsPartialUpdateRequestTypedDict,
    )
    from .clients_updateop import ClientsUpdateRequest, ClientsUpdateRequestTypedDict
    from .delete_bookingop import DeleteBookingRequest, DeleteBookingRequestTypedDict
    from .delete_clientop import DeleteClientRequest, DeleteClientRequestTypedDict
    from .delete_galleryop import DeleteGalleryRequest, DeleteGalleryRequestTypedDict
    from .delete_projectop import DeleteProjectRequest, DeleteProjectRequestTypedDict
    from .galleries_partial_updateop import (
        GalleriesPartialUpdateRequest,
        GalleriesPartialUpdateRequestTypedDict,
    )
    from .galleries_updateop import (
        GalleriesUpdateRequest,
        GalleriesUpdateRequestTypedDict,
    )
    from .gallery_input import GalleryInput, GalleryInputTypedDict
    from .gallery_output import (
        GalleryClient,
        GalleryClientTypedDict,
        GalleryOutput,
        GalleryOutputTypedDict,
        GalleryProject,
        GalleryProjectTypedDict,
    )
    from .gallerycreate import GalleryCreate, GalleryCreateTypedDict
    from .obtain_tokenop import ObtainTokenResponse, ObtainTokenResponseTypedDict
    from .patchedbooking import PatchedBooking, PatchedBookingTypedDict
    from .patchedclient import PatchedClient, PatchedClientTypedDict
    from .patchedgallery import PatchedGallery, PatchedGalleryTypedDict
    from .patchedproject import PatchedProject, PatchedProjectTypedDict
    from .project_input import ProjectInput, ProjectInputTypedDict
    from .project_output import (
        ProjectClient,
        ProjectClientTypedDict,
        ProjectOutput,
        ProjectOutputTypedDict,
    )
    from .projectcreate import ProjectCreate, ProjectCreateTypedDict
    from .projects_partial_updateop import (
        ProjectsPartialUpdateRequest,
        ProjectsPartialUpdateRequestTypedDict,
    )
    from .projects_updateop import ProjectsUpdateRequest, ProjectsUpdateRequestTypedDict
    from .projecttypeenum import ProjectTypeEnum
    from .refresh_tokenop import RefreshTokenResponse, RefreshTokenResponseTypedDict
    from .retrieve_bookingop import (
        RetrieveBookingRequest,
        RetrieveBookingRequestTypedDict,
    )
    from .retrieve_clientop import RetrieveClientRequest, RetrieveClientRequestTypedDict
    from .retrieve_galleryop import (
        RetrieveGalleryRequest,
        RetrieveGalleryRequestTypedDict,
    )
    from .retrieve_projectop import (
        RetrieveProjectRequest,
        RetrieveProjectRequestTypedDict,
    )
    from .security import Security, SecurityTypedDict
    from .tokenobtainpair import TokenObtainPair, TokenObtainPairTypedDict
    from .tokenrefresh import TokenRefresh, TokenRefreshTypedDict

__all__ = [
    "BookingClient",
    "BookingClientTypedDict",
    "BookingCreate",
    "BookingCreateTypedDict",
    "BookingInput",
    "BookingInputTypedDict",
    "BookingOutput",
    "BookingOutputTypedDict",
    "BookingProject",
    "BookingProjectTypedDict",
    "BookingsPartialUpdateRequest",
    "BookingsPartialUpdateRequestTypedDict",
    "BookingsUpdateRequest",
    "BookingsUpdateRequestTypedDict",
    "Client",
    "ClientCreate",
    "ClientCreateTypedDict",
    "ClientInput",
    "ClientInputTypedDict",
    "ClientTypedDict",
    "ClientsPartialUpdateRequest",
    "ClientsPartialUpdateRequestTypedDict",
    "ClientsUpdateRequest",
    "ClientsUpdateRequestTypedDict",
    "DeleteBookingRequest",
    "DeleteBookingRequestTypedDict",
    "DeleteClientRequest",
    "DeleteClientRequestTypedDict",
    "DeleteGalleryRequest",
    "DeleteGalleryRequestTypedDict",
    "DeleteProjectRequest",
    "DeleteProjectRequestTypedDict",
    "GalleriesPartialUpdateRequest",
    "GalleriesPartialUpdateRequestTypedDict",
    "GalleriesUpdateRequest",
    "GalleriesUpdateRequestTypedDict",
    "GalleryClient",
    "GalleryClientTypedDict",
    "GalleryCreate",
    "GalleryCreateTypedDict",
    "GalleryInput",
    "GalleryInputTypedDict",
    "GalleryOutput",
    "GalleryOutputTypedDict",
    "GalleryProject",
    "GalleryProjectTypedDict",
    "ObtainTokenResponse",
    "ObtainTokenResponseTypedDict",
    "PatchedBooking",
    "PatchedBookingTypedDict",
    "PatchedClient",
    "PatchedClientTypedDict",
    "PatchedGallery",
    "PatchedGalleryTypedDict",
    "PatchedProject",
    "PatchedProjectTypedDict",
    "ProjectClient",
    "ProjectClientTypedDict",
    "ProjectCreate",
    "ProjectCreateTypedDict",
    "ProjectInput",
    "ProjectInputTypedDict",
    "ProjectOutput",
    "ProjectOutputTypedDict",
    "ProjectTypeEnum",
    "ProjectsPartialUpdateRequest",
    "ProjectsPartialUpdateRequestTypedDict",
    "ProjectsUpdateRequest",
    "ProjectsUpdateRequestTypedDict",
    "RefreshTokenResponse",
    "RefreshTokenResponseTypedDict",
    "RetrieveBookingRequest",
    "RetrieveBookingRequestTypedDict",
    "RetrieveClientRequest",
    "RetrieveClientRequestTypedDict",
    "RetrieveGalleryRequest",
    "RetrieveGalleryRequestTypedDict",
    "RetrieveProjectRequest",
    "RetrieveProjectRequestTypedDict",
    "Security",
    "SecurityTypedDict",
    "TokenObtainPair",
    "TokenObtainPairTypedDict",
    "TokenRefresh",
    "TokenRefreshTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "BookingInput": ".booking_input",
    "BookingInputTypedDict": ".booking_input",
    "BookingClient": ".booking_output",
    "BookingClientTypedDict": ".booking_output",
    "BookingOutput": ".booking_output",
    "BookingOutputTypedDict": ".booking_output",
    "BookingProject": ".booking_output",
    "BookingProjectTypedDict": ".booking_output",
    "BookingCreate": ".bookingcreate",
    "BookingCreateTypedDict": ".bookingcreate",
    "BookingsPartialUpdateRequest": ".bookings_partial_updateop",
    "BookingsPartialUpdateRequestTypedDict": ".bookings_partial_updateop",
    "BookingsUpdateRequest": ".bookings_updateop",
    "BookingsUpdateRequestTypedDict": ".bookings_updateop",
    "Client": ".client",
    "ClientTypedDict": ".client",
    "ClientInput": ".client_input",
    "ClientInputTypedDict": ".client_input",
    "ClientCreate": ".clientcreate",
    "ClientCreateTypedDict": ".clientcreate",
    "ClientsPartialUpdateRequest": ".clients_partial_updateop",
    "ClientsPartialUpdateRequestTypedDict": ".clients_partial_updateop",
    "ClientsUpdateRequest": ".clients_updateop",
    "ClientsUpdateRequestTypedDict": ".clients_updateop",
    "DeleteBookingRequest": ".delete_bookingop",
    "DeleteBookingRequestTypedDict": ".delete_bookingop",
    "DeleteClientRequest": ".delete_clientop",
    "DeleteClientRequestTypedDict": ".delete_clientop",
    "DeleteGalleryRequest": ".delete_galleryop",
    "DeleteGalleryRequestTypedDict": ".delete_galleryop",
    "DeleteProjectRequest": ".delete_projectop",
    "DeleteProjectRequestTypedDict": ".delete_projectop",
    "GalleriesPartialUpdateRequest": ".galleries_partial_updateop",
    "GalleriesPartialUpdateRequestTypedDict": ".galleries_partial_updateop",
    "GalleriesUpdateRequest": ".galleries_updateop",
    "GalleriesUpdateRequestTypedDict": ".galleries_updateop",
    "GalleryInput": ".gallery_input",
    "GalleryInputTypedDict": ".gallery_input",
    "GalleryClient": ".gallery_output",
    "GalleryClientTypedDict": ".gallery_output",
    "GalleryOutput": ".gallery_output",
    "GalleryOutputTypedDict": ".gallery_output",
    "GalleryProject": ".gallery_output",
    "GalleryProjectTypedDict": ".gallery_output",
    "GalleryCreate": ".gallerycreate",
    "GalleryCreateTypedDict": ".gallerycreate",
    "ObtainTokenResponse": ".obtain_tokenop",
    "ObtainTokenResponseTypedDict": ".obtain_tokenop",
    "PatchedBooking": ".patchedbooking",
    "PatchedBookingTypedDict": ".patchedbooking",
    "PatchedClient": ".patchedclient",
    "PatchedClientTypedDict": ".patchedclient",
    "PatchedGallery": ".patchedgallery",
    "PatchedGalleryTypedDict": ".patchedgallery",
    "PatchedProject": ".patchedproject",
    "PatchedProjectTypedDict": ".patchedproject",
    "ProjectInput": ".project_input",
    "ProjectInputTypedDict": ".project_input",
    "ProjectClient": ".project_output",
    "ProjectClientTypedDict": ".project_output",
    "ProjectOutput": ".project_output",
    "ProjectOutputTypedDict": ".project_output",
    "ProjectCreate": ".projectcreate",
    "ProjectCreateTypedDict": ".projectcreate",
    "ProjectsPartialUpdateRequest": ".projects_partial_updateop",
    "ProjectsPartialUpdateRequestTypedDict": ".projects_partial_updateop",
    "ProjectsUpdateRequest": ".projects_updateop",
    "ProjectsUpdateRequestTypedDict": ".projects_updateop",
    "ProjectTypeEnum": ".projecttypeenum",
    "RefreshTokenResponse": ".refresh_tokenop",
    "RefreshTokenResponseTypedDict": ".refresh_tokenop",
    "RetrieveBookingRequest": ".retrieve_bookingop",
    "RetrieveBookingRequestTypedDict": ".retrieve_bookingop",
    "RetrieveClientRequest": ".retrieve_clientop",
    "RetrieveClientRequestTypedDict": ".retrieve_clientop",
    "RetrieveGalleryRequest": ".retrieve_galleryop",
    "RetrieveGalleryRequestTypedDict": ".retrieve_galleryop",
    "RetrieveProjectRequest": ".retrieve_projectop",
    "RetrieveProjectRequestTypedDict": ".retrieve_projectop",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "TokenObtainPair": ".tokenobtainpair",
    "TokenObtainPairTypedDict": ".tokenobtainpair",
    "TokenRefresh": ".tokenrefresh",
    "TokenRefreshTypedDict": ".tokenrefresh",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
