"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date
from fstop.types import BaseModel
from fstop.utils import FieldMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class BookingCreateTypedDict(TypedDict):
    r"""Serializer for creating bookings - excludes read-only fields (id, project, created_at)"""

    project_id: str
    r"""UUID of the project for this booking"""
    date_: date
    r"""Date of the booking"""
    time: str
    r"""Time of the booking"""
    duration: int
    r"""Booking duration in minutes"""
    location: str
    r"""Booking location"""


class BookingCreate(BaseModel):
    r"""Serializer for creating bookings - excludes read-only fields (id, project, created_at)"""

    project_id: Annotated[str, FieldMetadata(form=True, multipart=True)]
    r"""UUID of the project for this booking"""

    date_: Annotated[
        date, pydantic.Field(alias="date"), FieldMetadata(form=True, multipart=True)
    ]
    r"""Date of the booking"""

    time: Annotated[str, FieldMetadata(form=True, multipart=True)]
    r"""Time of the booking"""

    duration: Annotated[int, FieldMetadata(form=True, multipart=True)]
    r"""Booking duration in minutes"""

    location: Annotated[str, FieldMetadata(form=True, multipart=True)]
    r"""Booking location"""


try:
    BookingCreate.model_rebuild()
except NameError:
    pass
