"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .booking_input import BookingInput, BookingInputTypedDict
from fstop.types import BaseModel
from fstop.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class BookingsUpdateRequestTypedDict(TypedDict):
    id: str
    r"""Unique identifier of the resource."""
    body: BookingInputTypedDict


class BookingsUpdateRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique identifier of the resource."""

    body: Annotated[
        BookingInput,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
