"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .projecttypeenum import ProjectTypeEnum
from datetime import date, datetime
from fstop.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class BookingClientTypedDict(TypedDict):
    r"""Details of the client associated with this project"""

    id: str
    r"""Unique identifier for the client"""
    first_name: str
    r"""Client's first name"""
    last_name: str
    r"""Client's last name"""
    city: str
    r"""City where client is located"""
    state: str
    r"""State abbreviation (e.g., CA, NY)"""
    zip_code: str
    r"""Postal code for client's address"""
    email: str
    r"""Client's email address for contact"""
    phone_number: str
    r"""Client's phone number"""
    created_at: datetime
    r"""Timestamp when client was created"""


class BookingClient(BaseModel):
    r"""Details of the client associated with this project"""

    id: str
    r"""Unique identifier for the client"""

    first_name: str
    r"""Client's first name"""

    last_name: str
    r"""Client's last name"""

    city: str
    r"""City where client is located"""

    state: str
    r"""State abbreviation (e.g., CA, NY)"""

    zip_code: str
    r"""Postal code for client's address"""

    email: str
    r"""Client's email address for contact"""

    phone_number: str
    r"""Client's phone number"""

    created_at: datetime
    r"""Timestamp when client was created"""


class BookingProjectTypedDict(TypedDict):
    r"""Project associated with this booking"""

    id: str
    r"""Unique identifier for the project"""
    project_name: str
    r"""Name of the project"""
    project_type: ProjectTypeEnum
    r"""Type of project (event, portrait, or party)

    * `event` - event
    * `portrait` - portrait
    * `party` - party
    """
    client: BookingClientTypedDict
    r"""Details of the client associated with this project"""
    created_at: datetime
    r"""When the project was created"""


class BookingProject(BaseModel):
    r"""Project associated with this booking"""

    id: str
    r"""Unique identifier for the project"""

    project_name: str
    r"""Name of the project"""

    project_type: ProjectTypeEnum
    r"""Type of project (event, portrait, or party)

    * `event` - event
    * `portrait` - portrait
    * `party` - party
    """

    client: BookingClient
    r"""Details of the client associated with this project"""

    created_at: datetime
    r"""When the project was created"""


class BookingTypedDict(TypedDict):
    id: str
    r"""Unique identifier for the booking"""
    project: BookingProjectTypedDict
    r"""Project associated with this booking"""
    date_: date
    r"""Date of the booking"""
    time: str
    r"""Time of the booking"""
    duration: int
    r"""Booking duration in minutes"""
    location: str
    r"""Booking location"""
    created_at: datetime
    r"""When the booking was created"""


class Booking(BaseModel):
    id: str
    r"""Unique identifier for the booking"""

    project: BookingProject
    r"""Project associated with this booking"""

    date_: Annotated[date, pydantic.Field(alias="date")]
    r"""Date of the booking"""

    time: str
    r"""Time of the booking"""

    duration: int
    r"""Booking duration in minutes"""

    location: str
    r"""Booking location"""

    created_at: datetime
    r"""When the booking was created"""


try:
    Booking.model_rebuild()
except NameError:
    pass
