"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .client_input import ClientInput, ClientInputTypedDict
from fstop.types import BaseModel
from fstop.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class ClientsUpdateRequestTypedDict(TypedDict):
    id: str
    r"""Unique identifier of the resource."""
    body: ClientInputTypedDict


class ClientsUpdateRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique identifier of the resource."""

    body: Annotated[
        ClientInput,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
