"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from fstop.types import BaseModel
from fstop.utils import FieldMetadata
from typing_extensions import Annotated, TypedDict


class ClientCreateTypedDict(TypedDict):
    r"""Serializer for creating clients - excludes read-only fields (id, created_at)"""

    first_name: str
    r"""Client's first name"""
    last_name: str
    r"""Client's last name"""
    city: str
    r"""City where client is located"""
    state: str
    r"""State abbreviation (e.g., CA, NY)"""
    zip_code: str
    r"""Postal code for client's address"""
    email: str
    r"""Client's email address for contact"""
    phone_number: str
    r"""Client's phone number"""


class ClientCreate(BaseModel):
    r"""Serializer for creating clients - excludes read-only fields (id, created_at)"""

    first_name: Annotated[str, FieldMetadata(form=True, multipart=True)]
    r"""Client's first name"""

    last_name: Annotated[str, FieldMetadata(form=True, multipart=True)]
    r"""Client's last name"""

    city: Annotated[str, FieldMetadata(form=True, multipart=True)]
    r"""City where client is located"""

    state: Annotated[str, FieldMetadata(form=True, multipart=True)]
    r"""State abbreviation (e.g., CA, NY)"""

    zip_code: Annotated[str, FieldMetadata(form=True, multipart=True)]
    r"""Postal code for client's address"""

    email: Annotated[str, FieldMetadata(form=True, multipart=True)]
    r"""Client's email address for contact"""

    phone_number: Annotated[str, FieldMetadata(form=True, multipart=True)]
    r"""Client's phone number"""
