"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from fstop.types import BaseModel
from typing_extensions import TypedDict


class ClientTypedDict(TypedDict):
    id: str
    r"""Unique identifier for the client"""
    first_name: str
    r"""Client's first name"""
    last_name: str
    r"""Client's last name"""
    city: str
    r"""City where client is located"""
    state: str
    r"""State abbreviation (e.g., CA, NY)"""
    zip_code: str
    r"""Postal code for client's address"""
    email: str
    r"""Client's email address for contact"""
    phone_number: str
    r"""Client's phone number"""
    created_at: datetime
    r"""Timestamp when client was created"""


class Client(BaseModel):
    id: str
    r"""Unique identifier for the client"""

    first_name: str
    r"""Client's first name"""

    last_name: str
    r"""Client's last name"""

    city: str
    r"""City where client is located"""

    state: str
    r"""State abbreviation (e.g., CA, NY)"""

    zip_code: str
    r"""Postal code for client's address"""

    email: str
    r"""Client's email address for contact"""

    phone_number: str
    r"""Client's phone number"""

    created_at: datetime
    r"""Timestamp when client was created"""
