"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from fstop.types import BaseModel
from fstop.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class DeleteGalleryRequestTypedDict(TypedDict):
    id: str
    r"""Unique identifier of the resource."""


class DeleteGalleryRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique identifier of the resource."""
