"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .gallery_input import GalleryInput, GalleryInputTypedDict
from fstop.types import BaseModel
from fstop.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class GalleriesUpdateRequestTypedDict(TypedDict):
    id: str
    r"""Unique identifier of the resource."""
    body: GalleryInputTypedDict


class GalleriesUpdateRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique identifier of the resource."""

    body: Annotated[
        GalleryInput,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
