"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from fstop.types import BaseModel
from fstop.utils import FieldMetadata
from typing_extensions import Annotated, TypedDict


class GalleryCreateTypedDict(TypedDict):
    r"""Serializer for creating galleries - excludes read-only fields (id, project, created_at)"""

    project_id: str
    r"""UUID of the project for this gallery"""
    gallery_name: str
    r"""Name of the gallery"""
    picture_count: int
    r"""Number of pictures in the gallery"""
    is_visible: bool
    r"""Whether the gallery is publicly visible"""
    url: str
    r"""URL link to the gallery"""


class GalleryCreate(BaseModel):
    r"""Serializer for creating galleries - excludes read-only fields (id, project, created_at)"""

    project_id: Annotated[str, FieldMetadata(form=True, multipart=True)]
    r"""UUID of the project for this gallery"""

    gallery_name: Annotated[str, FieldMetadata(form=True, multipart=True)]
    r"""Name of the gallery"""

    picture_count: Annotated[int, FieldMetadata(form=True, multipart=True)]
    r"""Number of pictures in the gallery"""

    is_visible: Annotated[bool, FieldMetadata(form=True, multipart=True)]
    r"""Whether the gallery is publicly visible"""

    url: Annotated[str, FieldMetadata(form=True, multipart=True)]
    r"""URL link to the gallery"""
