"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .patchedbookingcreate import PatchedBookingCreate, PatchedBookingCreateTypedDict
from fstop.types import BaseModel, UNSET_SENTINEL
from fstop.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PartiallyUpdateBookingRequestTypedDict(TypedDict):
    id: str
    r"""A UUID string identifying this booking."""
    body: NotRequired[PatchedBookingCreateTypedDict]


class PartiallyUpdateBookingRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""A UUID string identifying this booking."""

    body: Annotated[
        Optional[PatchedBookingCreate],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["body"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
