"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from fstop.types import BaseModel, UNSET_SENTINEL
from fstop.utils import FieldMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PatchedClientCreateTypedDict(TypedDict):
    r"""Serializer for creating clients - excludes read-only fields (id, created_at)"""

    first_name: NotRequired[str]
    r"""Client's first name"""
    last_name: NotRequired[str]
    r"""Client's last name"""
    city: NotRequired[str]
    r"""City where client is located"""
    state: NotRequired[str]
    r"""State abbreviation (e.g., CA, NY)"""
    zip_code: NotRequired[str]
    r"""Postal code for client's address"""
    email: NotRequired[str]
    r"""Client's email address for contact"""
    phone_number: NotRequired[str]
    r"""Client's phone number"""


class PatchedClientCreate(BaseModel):
    r"""Serializer for creating clients - excludes read-only fields (id, created_at)"""

    first_name: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = (
        None
    )
    r"""Client's first name"""

    last_name: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = None
    r"""Client's last name"""

    city: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = None
    r"""City where client is located"""

    state: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = None
    r"""State abbreviation (e.g., CA, NY)"""

    zip_code: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = None
    r"""Postal code for client's address"""

    email: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = None
    r"""Client's email address for contact"""

    phone_number: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = (
        None
    )
    r"""Client's phone number"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "first_name",
                "last_name",
                "city",
                "state",
                "zip_code",
                "email",
                "phone_number",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
