"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from fstop.types import BaseModel, UNSET_SENTINEL
from fstop.utils import FieldMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PatchedGalleryCreateTypedDict(TypedDict):
    r"""Serializer for creating galleries - excludes read-only fields (id, project, created_at)"""

    project_id: NotRequired[str]
    r"""UUID of the project for this gallery"""
    gallery_name: NotRequired[str]
    r"""Name of the gallery"""
    picture_count: NotRequired[int]
    r"""Number of pictures in the gallery"""
    is_visible: NotRequired[bool]
    r"""Whether the gallery is publicly visible"""
    url: NotRequired[str]
    r"""URL link to the gallery"""


class PatchedGalleryCreate(BaseModel):
    r"""Serializer for creating galleries - excludes read-only fields (id, project, created_at)"""

    project_id: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = (
        None
    )
    r"""UUID of the project for this gallery"""

    gallery_name: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = (
        None
    )
    r"""Name of the gallery"""

    picture_count: Annotated[
        Optional[int], FieldMetadata(form=True, multipart=True)
    ] = None
    r"""Number of pictures in the gallery"""

    is_visible: Annotated[Optional[bool], FieldMetadata(form=True, multipart=True)] = (
        None
    )
    r"""Whether the gallery is publicly visible"""

    url: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = None
    r"""URL link to the gallery"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["project_id", "gallery_name", "picture_count", "is_visible", "url"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
