"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date
from fstop.types import BaseModel, UNSET_SENTINEL
from fstop.utils import FieldMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PatchedBookingCreateTypedDict(TypedDict):
    r"""Serializer for creating bookings - excludes read-only fields (id, project, created_at)"""

    project_id: NotRequired[str]
    r"""UUID of the project for this booking"""
    date_: NotRequired[date]
    r"""Date of the booking"""
    time: NotRequired[str]
    r"""Time of the booking"""
    duration: NotRequired[int]
    r"""Booking duration in minutes"""
    location: NotRequired[str]
    r"""Booking location"""


class PatchedBookingCreate(BaseModel):
    r"""Serializer for creating bookings - excludes read-only fields (id, project, created_at)"""

    project_id: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = (
        None
    )
    r"""UUID of the project for this booking"""

    date_: Annotated[
        Optional[date],
        pydantic.Field(alias="date"),
        FieldMetadata(form=True, multipart=True),
    ] = None
    r"""Date of the booking"""

    time: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = None
    r"""Time of the booking"""

    duration: Annotated[Optional[int], FieldMetadata(form=True, multipart=True)] = None
    r"""Booking duration in minutes"""

    location: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = None
    r"""Booking location"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["project_id", "date", "time", "duration", "location"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    PatchedBookingCreate.model_rebuild()
except NameError:
    pass
