"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .projecttypeenum import ProjectTypeEnum
from fstop.types import BaseModel, UNSET_SENTINEL
from fstop.utils import FieldMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PatchedProjectCreateTypedDict(TypedDict):
    r"""Serializer for creating projects - excludes read-only fields (id, client, created_at)"""

    project_name: NotRequired[str]
    r"""Name of the project"""
    project_type: NotRequired[ProjectTypeEnum]
    r"""Type of project (event, portrait, or party)

    * `event` - event
    * `portrait` - portrait
    * `party` - party
    """
    client_id: NotRequired[str]
    r"""UUID of the client for this project"""


class PatchedProjectCreate(BaseModel):
    r"""Serializer for creating projects - excludes read-only fields (id, client, created_at)"""

    project_name: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = (
        None
    )
    r"""Name of the project"""

    project_type: Annotated[
        Optional[ProjectTypeEnum], FieldMetadata(form=True, multipart=True)
    ] = None
    r"""Type of project (event, portrait, or party)

    * `event` - event
    * `portrait` - portrait
    * `party` - party
    """

    client_id: Annotated[Optional[str], FieldMetadata(form=True, multipart=True)] = None
    r"""UUID of the client for this project"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["project_name", "project_type", "client_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
