"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .project_input import ProjectInput, ProjectInputTypedDict
from fstop.types import BaseModel
from fstop.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class ProjectsUpdateRequestTypedDict(TypedDict):
    id: str
    r"""Unique identifier of the resource."""
    body: ProjectInputTypedDict


class ProjectsUpdateRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique identifier of the resource."""

    body: Annotated[
        ProjectInput,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
