"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .projecttypeenum import ProjectTypeEnum
from fstop.types import BaseModel
from fstop.utils import FieldMetadata
from typing_extensions import Annotated, TypedDict


class ProjectInputTypedDict(TypedDict):
    project_name: str
    r"""Name of the project"""
    project_type: ProjectTypeEnum
    r"""Type of project (event, portrait, or party)

    * `event` - event
    * `portrait` - portrait
    * `party` - party
    """
    client_id: str
    r"""UUID of the client for this project"""


class ProjectInput(BaseModel):
    project_name: Annotated[str, FieldMetadata(form=True, multipart=True)]
    r"""Name of the project"""

    project_type: Annotated[ProjectTypeEnum, FieldMetadata(form=True, multipart=True)]
    r"""Type of project (event, portrait, or party)

    * `event` - event
    * `portrait` - portrait
    * `party` - party
    """

    client_id: Annotated[str, FieldMetadata(form=True, multipart=True)]
    r"""UUID of the client for this project"""
