"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from fstop.types import UnrecognizedStr
from typing import Literal, Union


ProjectTypeEnum = Union[
    Literal[
        "event",
        "portrait",
        "party",
    ],
    UnrecognizedStr,
]
r"""* `event` - event
* `portrait` - portrait
* `party` - party
"""
