"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from fstop.types import BaseModel
from fstop.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class RetrieveClientRequestTypedDict(TypedDict):
    id: str
    r"""A UUID string identifying this client."""


class RetrieveClientRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""A UUID string identifying this client."""
