"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from fstop.types import BaseModel
from fstop.utils import FieldMetadata
from typing_extensions import Annotated, TypedDict


class TokenRefreshTypedDict(TypedDict):
    refresh: str


class TokenRefresh(BaseModel):
    refresh: Annotated[str, FieldMetadata(form=True, multipart=True)]
