"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from fstop.types import BaseModel
from fstop.utils import FieldMetadata
from typing_extensions import Annotated, TypedDict


class TokenObtainPairTypedDict(TypedDict):
    username: str
    password: str


class TokenObtainPair(BaseModel):
    username: Annotated[str, FieldMetadata(form=True, multipart=True)]

    password: Annotated[str, FieldMetadata(form=True, multipart=True)]
