"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .clientcreate import ClientCreate, ClientCreateTypedDict
from fstop.types import BaseModel
from fstop.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateClientRequestTypedDict(TypedDict):
    id: str
    r"""A UUID string identifying this client."""
    body: ClientCreateTypedDict


class UpdateClientRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""A UUID string identifying this client."""

    body: Annotated[
        ClientCreate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
