"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .gallerycreate import GalleryCreate, GalleryCreateTypedDict
from fstop.types import BaseModel
from fstop.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateGalleryRequestTypedDict(TypedDict):
    id: str
    r"""A UUID string identifying this gallery."""
    body: GalleryCreateTypedDict


class UpdateGalleryRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""A UUID string identifying this gallery."""

    body: Annotated[
        GalleryCreate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
