"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .bookingcreate import BookingCreate, BookingCreateTypedDict
from fstop.types import BaseModel
from fstop.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateBookingRequestTypedDict(TypedDict):
    id: str
    r"""A UUID string identifying this booking."""
    body: BookingCreateTypedDict


class UpdateBookingRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""A UUID string identifying this booking."""

    body: Annotated[
        BookingCreate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
