"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .projectcreate import ProjectCreate, ProjectCreateTypedDict
from fstop.types import BaseModel
from fstop.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateProjectRequestTypedDict(TypedDict):
    id: str
    r"""A UUID string identifying this project."""
    body: ProjectCreateTypedDict


class UpdateProjectRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""A UUID string identifying this project."""

    body: Annotated[
        ProjectCreate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
